### PR TITLE
aMule

### PR DESCRIPTION
**Pull request by fsteccanella**
Hi,
I've started to write this plugin for aMule...don't know if u may like it, but take a look! :D 
any suggestion is welcome...

### CODE REVIEW

**Comment by Hellowlol** [comment]
I think it's cool you wanna add stuff. I didn't even knew there was something called amule. I just remember emule. Is content to be on the ed2k network?

**Comment by sparklyballs** [comment]
I didn’t know about amule either until someone on unraid forum asked about putting it in a docker and I made an image for it.
I don’t use it, other than testing out new builds on the image etc…. it uses KAD and ED2K networks.

**Comment by fsteccanella** [comment]
yes..amule is the multiplatform version of emule..however i think that with some adjustement the plugin could works with all the versions of *mule...
the only hardlink with amule is the php snippet that can be easly adapted...

**Comment by Hellowlol** [comment]
Im gonna test this pr later as ed2k bring back memories.

**Comment by styxit** [comment]
700+ commits. Cant really merge that.

**Pull request closed without merging**
