### PR TITLE
Initial commit of headphones support.

### PR DESCRIPTION
**Pull request by djeebus**
Started adding basic support for headphones. Not sure I like the UI, but take a look, let me know what you think. I'm happy to make any changes requested!

Edit: Figured this needed a little bit more explanation. Here's what it currently supports:
* Add artist
* Lists artists
* List wanted albums
* Show details on artist, including number of tracks currently indexed, latest album, description, and album list, with current status)
* Mark album as "wanted"
* Album details, including track length and status

### CODE REVIEW

**Comment by kooimens** [comment]
@djeebus you see any chance to finish this? Maybe you can have a look at the maraschino project? It's in some way a comparable project and they include a Headphones module in the master branche.

**Comment by Hellowlol** [comment]
@kooimens have you tried the pr?

**Comment by kooimens** [comment]
Yes I have. And to be honest, it works like a charm on my PC, tablet and other mobile devices! I haven't test this PR with a headphones setup with a non-root user, but I will give it a try tonight. 

The only thing I was missing is the possibilty to add a release instead of an artist. This is useful if you want to add a various artists release. This feature will complete this PR for sure. 
And of course, if we have our upcoming shows and movies on our dashboard, it will be great to see any upcoming albums as well. 

I don't have any programming skills, but I do want to help you guys out with any testing (not only this HP pr). So let me know please!

**Comment by Hellowlol** [comment]
Thats great news. Testers are always needed, its hard to make sure that a request works on every plattform for something that you dont use yourself.

**Comment by kooimens** [comment]
Did some tests with different users and all working well. I didn't noticed any strange behaviour or api calls that didn't work on any device / browser (IE, chrome, firefox). 

Some remarks:
1. When looking up an album in htpc manager through the headphones plugin the default sorting is a bit strange. I couldn't figure out which sorting is being used, but it looks like the tracks of the albums are just randomly shown. One click on the track header solved this, but by default it should sort on track#. 
2. The UI leaves space for a artist and / or album image. However, it is not there.

Lastly, a dashboard item 'Wanted albums' will definetely be worth the effort. Looking at the couchpotato dashboard item it's only the moviename (no images). Maybe, it is not that hard to code? @Hellowlol

**Comment by Hellowlol** [comment]
Shouldnt be to hard, however i dont use hp, i installed it yesterday and I couldn't find shit or set anything as wanted so the motivation is definitely missing.

**Comment by kooimens** [comment]
Ok, yeah it's feels a bit buggy and slow when you start using it. You have to give it a try when the MusicBrainz servers are fast, that helps a lot. 

To come back to the Headphones PR:
3. I think a history tab is lacking. The couchpotato and sickbeard plugins have it both and it is very useful to see this kind of information. 
@styxit or @phillipbroberts you have time to help me out?

**Comment by Hellowlol** [comment]
@kooimems Since styxit and phillipbroberts hasn't responded I assume they don't have time to help you, I'll give you a hand. I'll finish the pr. I do have some stuff that I needed to finish first so I have no eta

**Comment by kooimens** [comment]
That's great! Let me know if I can help you with any testing

**Comment by Hellowlol** [comment]
Will do

**Comment by Hellowlol** [comment]
Headphones has been merged in this https://github.com/Hellowlol/HTPC-Manager Special thanks for @djeebus for making the inital pr and @kooimens for testing :)

**Pull request closed without merging**
